### ISSUE TITLE
Decide on a Python IDE for application development

### ISSUE THREAD

**Issue by dzakich** [DLWM-MSE/CPSC-544#2]
There are numerous IDEs available, both closed-srs and open-srs. 
I've heard a lot of good things about PyCharm IDE [https://www.jetbrains.com/pycharm/](url) with free access to Community Edition. Lynda.com has lots of resource available (i.e [https://www.lynda.com/Python-tutorials/Learning-Python-PyCharm/590828-2.html](url) )

But, As always, there are lots of other options. Perhaps some of you might already have experience with a proven IDE. Let us decide  🔍

**Comment by bengk** [comment]
You guys lead on this. I can research but I'm pretty new to Python.

**Comment by dzakich** [comment]
@bengk Eric, I believe we are all new to Python. This is why collaborative decision will actually contribute to overall learning since a little research need to be put into it

**Comment by bengk** [comment]
Sure okay. I'll look into it.

**Comment by dzakich** [comment]
@DLWM-MSE/alps 🆕 🐝s

**Comment by bengk** [comment]
I think I know what I'm using..
http://eric-ide.python-projects.org/

**Comment by dzakich** [comment]
There was a very sound recommendation to use Atom editor for our purpose given a fairly small-scope software product. Atom looks like a nice tool for Python as well.

**Comment by bengk** [comment]
Here is a youtube video on how to set up Atom for Python. 
I haven't finished watching it yet. 
https://www.youtube.com/watch?v=DjEuROpsvp4&feature=youtu.be

**Comment by dzakich** [comment]
@DLWM-MSE/alps Team has decided on Atom as our development environment.
