### ISSUE TITLE
.exe run as CMD terminal app does not parse color modifies

### ISSUE THREAD

**Issue by dzakich** [DLWM-MSE/CPSC-544#26]
Resources: 

1. https://en.wikipedia.org/wiki/ANSI_escape_code

2. https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences

3. https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#example

**Comment by dzakich** [comment]
![image](https://user-images.githubusercontent.com/13592198/30898160-aa304cde-a30e-11e7-85d7-2b56d2def24c.png)

Issue Screenshot

**Comment by dzakich** [comment]
Have a look @https://ourcodeworld.com/articles/read/273/how-to-create-an-executable-exe-from-a-python-script-in-windows-using-pyinstaller

**Comment by jlarceo40** [comment]
Issue fixed. Solution: Import Colorama module init, Fore, Back, Style and call init() within main. This fixes the issue of windows cmd not being able to recognize the ESC character '\' for the text modifiers.
