### ISSUE TITLE
Atom Text editor setup and usability assesment

### ISSUE THREAD

**Issue by dzakich** [DLWM-MSE/CPSC-544#3]
It's been decided to use Atom as a de-facto test editor for all Python-related project need. We must individually test and propose the best development setup for Atom environment. 
Atom can be downloaded from [atom.io](url)

**Comment by dzakich** [comment]
@DLWM-MSE/alps Eric's suggested video [https://www.youtube.com/watch?v=DjEuROpsvp4&feature=youtu.be](url) is super useful to installed necessary packages for python (i.e. linter and auto-pep8 compliance) as well as how to make Python scripts executable within the Atom itself

**Comment by dzakich** [comment]
Do you gents agree that we want to achieve somewhat identical functional configuration of the Atom environment? Not speaking of themes and suck but mostly of pep8 rules (Python style rules) and such?

**Comment by bengk** [comment]
Definitely. I haven't got around to using pip yet but I saw the video on it. Looks like, as he said, will minimize the differences in GitHub if we install this package and I'm sure it'll help us in learning the proper style guide.

**Comment by dzakich** [comment]
I agree. I read here and there that pep8 (Python Enhancements Proposals 8 : Code style for Python Language) for Python is de-facto standard for most developers. But I keep reading that _pep8_ pip package had been deprecated and replaced by _pycodestyle_ package
[https://pypi.python.org/pypi/pycodestyle](url)
Perhaps this is the style-checker we need to go with

**Comment by bengk** [comment]
[https://pypi.python.org/pypi/pycodestyle](url)

**Comment by bengk** [comment]
I'll have to check that out. 

*On an unrelated note. Does anyone else get sent a GitHub unrelated page when ever you click on a link in these comments?

**Comment by dzakich** [comment]
@bengk Yea, I noticed that embedded links don't work

**Comment by dzakich** [comment]
@DLWM-MSE/alps I have the following packages installed for Atom:

1. Script (for running Python in Atom) 
![image](https://user-images.githubusercontent.com/13592198/29744450-c4e41d8a-8a59-11e7-9427-d786da0a19e7.png)

2. autocomplete-python (for auto-complete functionality)
![image](https://user-images.githubusercontent.com/13592198/29744460-dff0dc9e-8a59-11e7-8509-ad6581c16f57.png)

3.  linte-pycodestyle (for linting code errors as you go)
![image](https://user-images.githubusercontent.com/13592198/29744470-f9d13d3e-8a59-11e7-99fc-61e15a1c5cc8.png)

4. python-autopep8 (for automatic and *uniform* formatting of all Python code. Offers immediate benefits for Git collaboration when we have to resolve merge issues, etc)
![image](https://user-images.githubusercontent.com/13592198/29744472-015bc07e-8a5a-11e7-8ef2-b9e8c2885b6a.png)

**Comment by dzakich** [comment]
@DLWM-MSE/alps 
All members of the team have installed, configured, and accepted team-defined Atom's configuration.
The issue is closed.
